### ISSUE TITLE
 Missing translation

### ISSUE THREAD

**Issue by isaacpompa** [cursame/cursame-issues#51]
![captura de pantalla 2015-05-25 a la s 17 50 22](https://cloud.githubusercontent.com/assets/5297119/7802948/e7e6c318-0307-11e5-9359-8e748c55ac57.png)
![captura de pantalla 2015-05-25 a la s 17 50 34](https://cloud.githubusercontent.com/assets/5297119/7802946/e7e61c10-0307-11e5-9a3e-842c1abc2208.png)
![captura de pantalla 2015-05-25 a la s 17 50 29](https://cloud.githubusercontent.com/assets/5297119/7802947/e7e68c90-0307-11e5-8d8c-8a7251f01868.png)

En la pantalla de inicio de la plataforma, cuando quieres asociar un formulario a un curso y no existen cursos en la red, aparecen traducciones faltantes.

**Comment by nachotl** [comment]
¿Cómo vamos? Tenemos fecha de entrega de traducciones al 100%, no veo avanzar esto.
